version: 0.0
os: linux
files:
    - source: /
      destination: /app/nodeappexample
hooks:
  ApplicationStop:
    - location: /scripts/start_application.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: /scripts/stop_application.sh
      timeout: 180
      runas: root
  
